"""empty message

Revision ID: 515ff26101f1
Revises: 9cb5e9474095
Create Date: 2023-05-18 15:55:27.976171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515ff26101f1'
down_revision = '9cb5e9474095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('thumbnail',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('thumbnail',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
